import os
import re

p = r"C:\Users\akula\Downloads\Hide-WIN - Copy\Hide-Win-Web\src\pages\Admin.jsx"

with open(p, "r", encoding="utf-8") as f:
    text = f.read()

# Add the Globe icon if it's not imported (lucide-react)
if "Globe," not in text and "Globe " not in text:
    text = text.replace("import { ", "import { Globe, ")

# 1. Add the sidebar button
sidebar_btn = """                <button className={`settings-nav-item ${activeSettingsTab === 'dns' ? 'active' : ''}`} onClick={() => setActiveSettingsTab('dns')}>
                  <Globe size={18} /> DNS & Network
                </button>
"""
if "setActiveSettingsTab('dns')" not in text:
    text = text.replace(
        "              </aside>", 
        sidebar_btn + "              </aside>"
    )

# 2. Add the content block
content_block = """
                {/* DNS & NETWORK */}
                {activeSettingsTab === 'dns' && (
                  <div className="fade-in">
                    <div style={{ marginBottom: '24px' }}>
                      <h2 style={{ fontSize: '24px', fontWeight: 700, marginBottom: '8px' }}>DNS & Network Configuration</h2>
                      <p style={{ color: 'var(--text-muted)' }}>Configure local or remote server settings for WebRTC signaling and collaboration across devices.</p>
                    </div>

                    <div className="card">
                      <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px' }}>WebRTC Signaling Server</h3>
                      <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '16px' }}>
                        Set the IP and Port where your local Python WebSocket server is running. This will be embedded into the Invite links generated by the Desktop app.
                      </p>

                      <div className="input-group">
                        <label className="input-label">Server IP Address (e.g. 192.168.1.10)</label>
                        <input type="text" className="input-field" placeholder="127.0.0.1" value={appSettings?.dns_ip || '127.0.0.1'} onChange={(e) => handleSettingChange('dns_ip', e.target.value)} />
                      </div>

                      <div className="input-group">
                        <label className="input-label">Server Port</label>
                        <input type="text" className="input-field" placeholder="8001" value={appSettings?.dns_port || '8001'} onChange={(e) => handleSettingChange('dns_port', e.target.value)} />
                      </div>

                      <div className="input-group" style={{ marginBottom: 0 }}>
                        <label className="input-label">Custom Domain (Future VPC/AWS)</label>
                        <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '8px' }}>Optional. If provided, the app uses this domain instead of the IP address (e.g. hidewin.com).</p>
                        <input type="text" className="input-field" placeholder="hidewin.com" value={appSettings?.dns_domain || ''} onChange={(e) => handleSettingChange('dns_domain', e.target.value)} />
                      </div>
                    </div>
                  </div>
                )}
"""

if "DNS & NETWORK" not in text:
    text = text.replace(
        "                {/* ADVANCED ARCHITECTURE */}", 
        content_block + "\n                {/* ADVANCED ARCHITECTURE */}"
    )

with open(p, "w", encoding="utf-8") as f:
    f.write(text)

print("Updated Admin.jsx with DNS settings")
