const fs = require('fs');
const p = 'C:\\Users\\akula\\Downloads\\Hide-WIN - Copy\\Hide-Win-Web\\src\\pages\\Admin.jsx';
let text = fs.readFileSync(p, 'utf8');

// 1. Inject the Sidebar Button
const sidebarBtn = `
                <button className={\`settings-nav-item \${activeSettingsTab === 'dns' ? 'active' : ''}\`} onClick={() => setActiveSettingsTab('dns')}>
                  <Globe size={18} /> DNS & Network
                </button>`;

if (!text.includes("setActiveSettingsTab('dns')")) {
    // Find the end of the sidebar
    text = text.replace(/<\/aside>/, sidebarBtn + '\n              </aside>');
}

// 2. Inject the Content Block
const contentBlock = `
                {/* DNS & NETWORK */}
                {activeSettingsTab === 'dns' && (
                  <div className="fade-in">
                    <div style={{ marginBottom: '24px' }}>
                      <h2 style={{ fontSize: '24px', fontWeight: 700, marginBottom: '8px' }}>DNS & Network Configuration</h2>
                      <p style={{ color: 'var(--text-muted)' }}>Configure local or remote server settings for WebRTC signaling and collaboration across devices.</p>
                    </div>

                    <div className="card">
                      <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px' }}>WebRTC Signaling Server</h3>
                      <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '16px' }}>
                        Set the IP and Port where your local Python WebSocket server is running. This will be embedded into the Invite links generated by the Desktop app.
                      </p>

                      <div className="input-group">
                        <label className="input-label">Server IP Address (e.g. 192.168.1.10)</label>
                        <input type="text" className="input-field" placeholder="127.0.0.1" value={appSettings?.dns_ip || ''} onChange={(e) => handleSettingChange('dns_ip', e.target.value)} />
                      </div>

                      <div className="input-group">
                        <label className="input-label">Server Port</label>
                        <input type="text" className="input-field" placeholder="8001" value={appSettings?.dns_port || ''} onChange={(e) => handleSettingChange('dns_port', e.target.value)} />
                      </div>

                      <div className="input-group" style={{ marginBottom: 0 }}>
                        <label className="input-label">Custom Domain (Future VPC/AWS)</label>
                        <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '8px' }}>Optional. If provided, the app uses this domain instead of the IP address (e.g. hidewin.com).</p>
                        <input type="text" className="input-field" placeholder="hidewin.com" value={appSettings?.dns_domain || ''} onChange={(e) => handleSettingChange('dns_domain', e.target.value)} />
                      </div>
                    </div>
                  </div>
                )}
`;

if (!text.includes("DNS & NETWORK")) {
    text = text.replace(/\{\/\*\s*ADVANCED ARCHITECTURE\s*\*\/\}/, contentBlock + '\n                {/* ADVANCED ARCHITECTURE */}');
}

fs.writeFileSync(p, text, 'utf8');
console.log("Injected DNS block using robust matching.");
