"""Add email templates

Revision ID: 18734f646942
Revises: 
Create Date: 2026-09-20 22:36:32.274531

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '18734f646942'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_invite_tokens_id'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_api_configs_key'), table_name='api_configs')
    op.drop_table('api_configs')
    op.drop_index(op.f('ix_session_participants_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_setting_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_ai_provider_keys_id'), table_name='ai_provider_keys')
    op.drop_index(op.f('ix_ai_provider_keys_provider'), table_name='ai_provider_keys')
    op.drop_table('ai_provider_keys')
    op.drop_index(op.f('ix_token_billing_id'), table_name='token_billing')
    op.drop_table('token_billing')
    op.drop_index(op.f('ix_work_reports_id'), table_name='work_reports')
    op.drop_table('work_reports')
    op.drop_index(op.f('ix_shadow_context_id'), table_name='shadow_context')
    op.drop_table('shadow_context')
    op.drop_index(op.f('ix_stt_provider_keys_id'), table_name='stt_provider_keys')
    op.drop_index(op.f('ix_stt_provider_keys_provider_name'), table_name='stt_provider_keys')
    op.drop_table('stt_provider_keys')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_platform'), table_name='integrations')
    op.drop_table('integrations')
    op.add_column('users', sa.Column('failed_otp_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_block_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('admin_unblock_required', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'last_logged_in')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'session_purpose')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'vendor_id')
    op.drop_column('users', 'logo_url')
    op.drop_column('users', 'context_data')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'allocated_seats')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('allocated_seats', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('users', sa.Column('theme', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('context_data', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('logo_url', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('vendor_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('session_purpose', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('last_logged_in', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['vendor_id'], ['id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'admin_unblock_required')
    op.drop_column('users', 'blocked_until')
    op.drop_column('users', 'otp_block_level')
    op.drop_column('users', 'failed_otp_attempts')
    op.create_table('integrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(), nullable=True),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_platform'), 'integrations', ['platform'], unique=False)
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_table('stt_provider_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider_name', sa.VARCHAR(), nullable=True),
    sa.Column('api_key_value', sa.VARCHAR(), nullable=True),
    sa.Column('custom_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('mode', sa.TEXT(), server_default=sa.text("'local_ws'"), nullable=True),
    sa.Column('encrypted_key', sa.TEXT(), nullable=True),
    sa.Column('key_hint', sa.TEXT(), nullable=True),
    sa.Column('custom_name', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('buffer_seconds', sa.INTEGER(), server_default=sa.text('3'), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.Column('enabled_models', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stt_provider_keys_provider_name'), 'stt_provider_keys', ['provider_name'], unique=False)
    op.create_index(op.f('ix_stt_provider_keys_id'), 'stt_provider_keys', ['id'], unique=False)
    op.create_table('shadow_context',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('active_ide_code', sa.TEXT(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_context_id'), 'shadow_context', ['id'], unique=False)
    op.create_table('work_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('report_type', sa.VARCHAR(), nullable=True),
    sa.Column('summary_data', sqlite.JSON(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_reports_id'), 'work_reports', ['id'], unique=False)
    op.create_table('token_billing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True),
    sa.Column('estimated_cost_usd', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_billing_id'), 'token_billing', ['id'], unique=False)
    op.create_table('ai_provider_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('custom_url', sa.VARCHAR(), nullable=True),
    sa.Column('api_key_value', sa.VARCHAR(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('quota_usage', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('enabled_models', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_provider_keys_provider'), 'ai_provider_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_provider_keys_id'), 'ai_provider_keys', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('next_billing_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('setting_key', sa.VARCHAR(), nullable=True),
    sa.Column('setting_value', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_setting_key'), 'app_settings', ['setting_key'], unique=1)
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('actor_email', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('encrypted_payload', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('goal_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('mac_address', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('trial_hits', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mac_address')
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=False)
    op.create_table('session_participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_id'), 'session_participants', ['id'], unique=False)
    op.create_table('api_configs',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('modified_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_api_configs_key'), 'api_configs', ['key'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('goal_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('pomodoro_sessions', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('jira_ticket_ref', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('invited_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('used', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=1)
    op.create_index(op.f('ix_invite_tokens_id'), 'invite_tokens', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('price_monthly', sa.FLOAT(), nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(), nullable=True),
    sa.Column('features', sqlite.JSON(), nullable=True),
    sa.Column('seat_limit', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=1)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=1)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    # ### end Alembic commands ###
